import { body } from "express-validator";

export const validarClase = [
  body("nombre")
    .exists()
    .withMessage("Es obligatorio")
    .bail()
    .isString()
    .withMessage("Debe ser un texto")
    .bail()
    .notEmpty()
    .withMessage("No debe estar vacio"),
  body("descripcion")
    .exists()
    .withMessage("Es obligatorio")
    .bail()
    .isString()
    .withMessage("Debe ser un texto")
    .bail()
    .notEmpty()
    .withMessage("No debe estar vacio"),
  body("entrenadorId")
    .exists()
    .withMessage("Es obligatorio")
    .bail()
    .isString()
    .withMessage("Debe ser un texto")
    .bail()
    .notEmpty()
    .withMessage("No debe estar vacio")
    .bail(),
  body("horario")
    .exists()
    .withMessage("Es obligatorio")
    .bail()
    .isString()
    .withMessage("Debe ser un texto")
    .bail()
    .notEmpty()
    .withMessage("No debe estar vacio")
    .bail(),
  body("cuposDisponibles")
    .exists()
    .withMessage("Es obligatorio")
    .bail()
    .isInt({ min: 1 })
    .withMessage("Debe ser un numero")
    .bail()
    .notEmpty()
    .withMessage("No debe estar vacio")
    .bail()
];
